network_list = [
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "bc945a30f0f6592727d4752ecedbe0b1"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "41f222bfe675f10c038e668167848c85"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "1295162607c66f092bafa705fcc9e406"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "e12ce5eb163d50a7520524716248c558"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "ab2f4f118ab70e9fc5f426543c055416"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "63c5ceb68b001c2a98db309eb9d7c4b9"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "5a9e368a43e3ff841bbb8dac3cc1254c"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "5706148d9e93cc41ce218f7a78f37b09"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "9ac76bca3b1aef392c8ffe71473d1072"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "eae83c0029a6397afd56fe75a04b9a9c"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "0e19cd749d67d0924fb9265f8cb933b1"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "0feefbdac98b7f4d4158d65b6ea61674"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "acc9bd366979db49bad0326ded459086"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "bc3d029fdfc5d277b36c8f980620adad"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "b6777f950af35e035ab3bb23bb106f2f"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "f6a17df0037fbc5ab65dbea84b54e26f"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "8438fdae539b4fece27056e5d6426ec3"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "1f284d518299d821b8b5ade7f927b96c"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "b89ac351a66aebe2e7858d37234138ea"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "64a85adfbcaf6c24bc108b17996371be"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "ea605703f04bf72111a0050b380aec3e"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "6eae54d490c5bb039fad4f8ad9bf1308"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "090bd8ff4877b4bff7902afdd6acb3ad"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "6c83765f98db6c07bdba516e26929f1d"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "75cb06cc8093a6baf65d7a2b712395a4"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "74a43825daa642eb7b98a0e64b9d679a"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "e979bbcf2878048ff82a15c6399a9a62"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "7df867203515c9e4db8bf8f8717b6f61"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "ad0a89c0b057167a5eb0bc5f8de6f01a"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "39552b8398bb9d11f720efc8559081ec"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "c458721dd89df8a9b82a6bcff3cb2d11"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "5006b4ac19d1d524b582d350b1d76271"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "c096cd0380e4ac3450d99c35e2f34696"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "90d05c83d17c8f63ce1946fb65bb966f"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "9b9f1ec179c9dde4857df0a0bdee9f8e"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "38e2f44ff2c77ff9253a775f2a114df5"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "6cef6b320e2b3026dc7cd10a39e14885"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "4aac1810ba9d299c28e36ecbb1169b8c"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "484e98d797d288bd19848bf615d8bfc8"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "bfde4b609dfdc43525bcad2a91738656"
  },
  {
    "http2" : "on",
    "always_use_https" : "on",
    "automatic_https_rewrites" : "off",
    "http3" : "on",
    "zero_rtt" : "on",
    "ipv6" : "on",
    "websockets" : "on",
    "opportunistic_onion" : "off",
    "pseudo_ipv4" : "off",
    "ip_geolocation" : "on",
    "max_upload" : 100,
    "response_buffering" : "off",
    "true_client_ip_header" : "on",
    "polish" : "lossy",
    "webp" : "on",
    "h2_prioritization" : "on",
    "rocket_loader" : "off",
    "brotli" : "on",
    "minify" : {
      "css" : "on",
      "js" : "on",
      "html" : "off"
    },
    "zone_id" : "48bc337f0ab09bce2c71da1550ab78c1"
  }
]
